сущности для груп модифаер
QEEP-Pro/QEEPApiClient pull request #18
Opened 2021-11-02 06:35 UTC by KulEugene

2021-11-03 17:02 UTC, sivolobov requested changes

2021-11-03 17:02 UTC, sivolobov commented on src/V2/Model/GroupModifier.php
> +    public function getIikoId()
Это что и зачем здесь?

2021-11-03 17:02 UTC, sivolobov commented on src/V2/Model/GroupModifier.php
> +        }
Этот функионал точно не будет работать на обычных примитивных массивах. Если используешь ArrayCollection, то обозначь это (в описании переменной, в типах, добавь инициализацию пустого ArrayCollection в конструкторе). Если нигде в проекте не используется ArrayCollection, то ради такой мелочи его добавлять точно не стоит.

2021-11-23 08:09 UTC, KulEugene commented on src/V2/Model/GroupModifier.php
> +    public function getIikoId()
+

2021-11-24 07:39 UTC, sivolobov approved these changes

2021-11-24 07:40 UTC, merged